name: frontend
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  form_field_validator: ^1.1.0
  http: ^0.13.5
  shared_preferences: ^2.0.18
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  meta: ^1.2.3
  flutter: 
    sdk: flutter
  provider: ^6.0.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/landing.jpg
    - assets/images/login.jpg
    - assets/images/landingpage.png

  fonts:
    - family: Poppins
      fonts:
        - asset : assets/fonts/poppins/Poppins-Regular.ttf